
# Compiler settings
CC = gcc
# -MMD -MP generates dependency (.d) files automatically
CFLAGS = -Wall -Wextra -O2 -std=c99 -MMD -MP 
LIBS = -lm -lSDL3

# Targets
TARGET = main
TEST_TARGET = test

# Source files (Removed squares.c)
SOURCES = main.c alg.c gameloop.c entities.c handle_input.c projection_math.c camera.c
TEST_SOURCES = test.c alg.c

# Object files (Automatically generated from SOURCES)
OBJECTS = $(SOURCES:.c=.o)
TEST_OBJECTS = $(TEST_SOURCES:.c=.o)

# Dependency files (Generated by the compiler)
DEPS = $(OBJECTS:.o=.d) $(TEST_OBJECTS:.o=.d)

# --- Build Rules ---

# Default target
all: $(TARGET)

# Link the main executable
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)
	@echo "✓ Built $(TARGET)"

# Link the test executable
test: $(TEST_OBJECTS)
	$(CC) $(CFLAGS) -o $(TEST_TARGET) $^ $(LIBS)
	@echo "✓ Built $(TEST_TARGET)"

# Generic Rule: Compiles any .c file into a .o file
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# --- Utility Targets ---

run: $(TARGET)
	./$(TARGET)

run-test: test
	./$(TEST_TARGET)

clean:
	rm -f $(OBJECTS) $(TEST_OBJECTS) $(DEPS) $(TARGET) $(TEST_TARGET)
	@echo "✓ Cleaned build artifacts"

rebuild: clean all

help:
	@echo "Available targets:"
	@echo "  make all       - Build the main executable"
	@echo "  make run       - Build and run the game"
	@echo "  make test      - Build the test suite"
	@echo "  make run-test  - Run the test suite"
	@echo "  make clean     - Remove all build files"

# Include the dependency files tracked by the compiler
# The dash (-) silences errors if the .d files don't exist yet
-include $(DEPS)

.PHONY: all test run run-test clean rebuild help