# Compiler settings
CC = gcc
# -MMD -MP generates dependency (.d) files automatically
CFLAGS = -Wall -Wextra -O3 -std=gnu99 -MMD -MP -msse4.1 -march=native -mfpmath=sse -ffast-math -funroll-loops -fvisibility=hidden
LIBS = -lm -lSDL3

# Directories
SRC_DIR   = src
INC_DIR   = headers
BUILD_DIR = build

CFLAGS += -I$(INC_DIR)

# Targets
TARGET = main
TEST_TARGET = test

# Source files — auto-discovered from src/, test.c excluded from the main build
SOURCES := $(filter-out $(SRC_DIR)/test.c, $(wildcard $(SRC_DIR)/*.c))
TEST_SOURCES = $(SRC_DIR)/test.c $(SRC_DIR)/alg.c

# Object files land in build/, mirroring src/ (Automatically generated from SOURCES)
OBJECTS      = $(SOURCES:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
TEST_OBJECTS = $(TEST_SOURCES:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)

# Dependency files (Generated by the compiler)
DEPS = $(OBJECTS:.o=.d) $(TEST_OBJECTS:.o=.d)

# --- Build Rules ---

# Default target
all: $(TARGET)

# Link the main executable
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)
	@echo "✓ Built $(TARGET)"

# Link the test executable
test: $(TEST_OBJECTS)
	$(CC) $(CFLAGS) -o $(TEST_TARGET) $^ $(LIBS)
	@echo "✓ Built $(TEST_TARGET)"

# Generic Rule: Compiles any src/*.c file into a build/*.o file
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Ensure the build directory exists
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# --- Utility Targets ---

run: $(TARGET)
	./$(TARGET)

run-test: test
	./$(TEST_TARGET)

clean:
	rm -rf $(BUILD_DIR) $(TARGET) $(TEST_TARGET)
	@echo "✓ Cleaned build artifacts"

rebuild: clean all

help:
	@echo "Available targets:"
	@echo "  make all       - Build the main executable"
	@echo "  make run       - Build and run the game"
	@echo "  make test      - Build the test suite"
	@echo "  make run-test  - Run the test suite"
	@echo "  make clean     - Remove all build files"

# Include the dependency files tracked by the compiler
# The dash (-) silences errors if the .d files don't exist yet
-include $(DEPS)

.PHONY: all test run run-test clean rebuild help
